<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <WasmEnableHotReload>false</WasmEnableHotReload>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Audio/Foster.Audio.Web.csproj" />
    <Content Include="wwwroot/**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <Import Project="../../Audio/Foster.Audio.Web.targets" />
</Project>
