
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.game
{
public sealed partial class fruit : Luban.BeanBase
{
    public fruit(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Radius = _buf.GetProperty("radius").GetSingle();
        Score = _buf.GetProperty("score").GetInt32();
        SwordIntent = _buf.GetProperty("sword_intent").GetInt32();
        GrowthReward = _buf.GetProperty("growth_reward").GetSingle();
        TimeBonus = _buf.GetProperty("time_bonus").GetSingle();
        ColorR = _buf.GetProperty("color_r").GetSingle();
        ColorG = _buf.GetProperty("color_g").GetSingle();
        ColorB = _buf.GetProperty("color_b").GetSingle();
        RenderScale = _buf.GetProperty("render_scale").GetSingle();
        SpawnWeight = _buf.GetProperty("spawn_weight").GetInt32();
    }

    public static fruit Deserializefruit(JsonElement _buf)
    {
        return new game.fruit(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 分数
    /// </summary>
    public readonly int Score;
    /// <summary>
    /// 剑意
    /// </summary>
    public readonly int SwordIntent;
    /// <summary>
    /// 树成长
    /// </summary>
    public readonly float GrowthReward;
    /// <summary>
    /// 加时(秒)
    /// </summary>
    public readonly float TimeBonus;
    /// <summary>
    /// 颜色R
    /// </summary>
    public readonly float ColorR;
    /// <summary>
    /// 颜色G
    /// </summary>
    public readonly float ColorG;
    /// <summary>
    /// 颜色B
    /// </summary>
    public readonly float ColorB;
    /// <summary>
    /// 渲染缩放
    /// </summary>
    public readonly float RenderScale;
    /// <summary>
    /// 生成权重
    /// </summary>
    public readonly int SpawnWeight;
   
    public const int __ID__ = -444469480;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "radius:" + Radius + ","
        + "score:" + Score + ","
        + "swordIntent:" + SwordIntent + ","
        + "growthReward:" + GrowthReward + ","
        + "timeBonus:" + TimeBonus + ","
        + "colorR:" + ColorR + ","
        + "colorG:" + ColorG + ","
        + "colorB:" + ColorB + ","
        + "renderScale:" + RenderScale + ","
        + "spawnWeight:" + SpawnWeight + ","
        + "}";
    }
}
}

