
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.game
{
public partial class Tbfruit
{
    private readonly System.Collections.Generic.Dictionary<int, game.fruit> _dataMap;
    private readonly System.Collections.Generic.List<game.fruit> _dataList;
    
    public Tbfruit(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataMap = new System.Collections.Generic.Dictionary<int, game.fruit>(count);
        _dataList = new System.Collections.Generic.List<game.fruit>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            game.fruit _v;
            _v = global::cfg.game.fruit.Deserializefruit(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, game.fruit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<game.fruit> DataList => _dataList;

    public game.fruit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public game.fruit Get(int key) => _dataMap[key];
    public game.fruit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

