<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Libs\Engine\Engine.csproj" />
    <ProjectReference Include="..\..\..\Libs\Engine.ECS\Engine.ECS.csproj" />
    <ProjectReference Include="..\..\..\Libs\ThirdParty\Box2D\DragonLib.Box2D.csproj" />
    <Compile Include="..\Content\JobSchedulerBox2DTasks.cs" Link="Shared\JobSchedulerBox2DTasks.cs" />
    <ProjectReference Include="..\..\..\Libs\ThirdParty\Gltf\DragonLib.Gltf.csproj" />
    <ProjectReference Include="..\..\..\Libs\ThirdParty\Spine\DragonLib.Spine.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
